name: CI Release Next to Azure SWA

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      # Step 2: Build and Deploy to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_QA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: "yarn build"
          app_location: "/" # App source code path
          output_location: ".output/public" # Built app content directory - optional
          api_location: ".output/server" # Api source code path - optional
          ###### End of Repository/Build Configurations ######
        env:
          GEINS_API_URL: ${{ vars.GEINS_API_URL_QA }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_PATH: ${{ vars.AZURE_GEINS_AUTH_PATH }}
          BASE_URL: ${{ vars.AZURE_GEINS_BASE_URL_QA }}
          GEINS_DEBUG: ${{ vars.AZURE_GEINS_DEBUG_QA }}
          NITRO_PRESET: ${{ vars.NITRO_PRESET_AZURE_SWA }}
