name: CI Release Next to Azure SWA

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - next

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      GEINS_API_URL: ${{ vars.GEINS_API_URL_QA }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_ORIGIN: ${{ vars.AZURE_GEINS_AUTH_ORIGIN_QA }}
      GEINS_DEBUG: ${{ vars.AZURE_GEINS_DEBUG_QA }}
      NITRO_PRESET: ${{ vars.NITRO_PRESET_AZURE_SWA }}
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Build and Deploy to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_QA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: 'yarn build'
          app_location: '/' # App source code path
          output_location: '.output/public' # Built app content directory - optional
          api_location: '.output/server' # Api source code path - optional
          ###### End of Repository/Build Configurations ######

      # Step 3: Post to Slack
      - name: Post to Slack
        if: github.event_name == 'push'
        id: posttoslack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          URL: ${{ vars.AZURE_GEINS_AUTH_ORIGIN_QA }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
          "text": "*The QA site has been updated!* :unicorn_face:\n\n:point_right: <'"$URL"'|'"$URL"'> :point_left:"
          }' $SLACK_WEBHOOK_URL

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_QA_TOKEN }}
          action: 'close'
