name: Docs Release
on: workflow_dispatch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust to your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Update documentation versions
      - name: Update documentation
        run: yarn docs:update

      # Step 5: Commit and push changes
      - name: Commit and push updated docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/packages/index.md
          git diff --quiet && echo "No changes to commit" || git commit -m "Update docs with package versions"
          git push

      # Step 6: Build and Deploy to Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: '/' # App source code path
          app_build_command: 'npm run docs:build'
          api_location: '' # Api source code path - optional
          output_location: 'docs/.vitepress/dist' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
